spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:api_sentinel}
    username: ${DB_USERNAME:sentinel_user}
    password: ${DB_PASSWORD:sentinel_dev_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    com.apisentinel: INFO
    org.springframework.web: INFO
